### ISSUE TITLE
5.4 Branch ? 

### ISSUE THREAD

**Issue by gkowalski** [omoponfhir/omoponfhir-omopv5-sql#12]
Is the 5.4 branch compatible with an OMOP 5.4 database ?  I'm getting the following error with the master branch in this repo : 

```
Caused by: org.postgresql.util.PSQLException: ERROR: column visitoccurrence.admitting_source_concept_id does not exist
  Position: 6868
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:236)
	at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
	at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
	at edu.gatech.chai.omopv5.dba.service.BaseEntityServiceImp.runQuery(BaseEntityServiceImp.java:168)
	at edu.gatech.chai.omopv5.dba.service.BaseEntityServiceImp.searchEntity(BaseEntityServiceImp.java:643)
	at edu.gatech.chai.omopv5.dba.service.BaseEntityServiceImp.searchWithParams(BaseEntityServiceImp.java:1292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy29.searchWithParams(Unknown Source)
	at edu.gatech.chai.omoponfhir.omopv5.r4.mapping.OmopObservation.searchWithParams(OmopObservation.java:1893)
	at edu.gatech.chai.omoponfhir.omopv5.r4.provider.ObservationResourceProvider$MyBundleProvider.getResources(ObservationResourceProvider.java:372)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.createBundleFromBundleProvider(BaseResourceReturningMethodBinding.java:198)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:389)
	... 27 more
```

trying to deploy https://github.com/omoponfhir/omoponfhir-main-r4-sql.git ( main Branch ) with a pom.xml of : 
```
  <modules>
                <module>omoponfhir-omopv5-sql</module>
                <module>omoponfhir-omopv5-r4-mapping</module>
                <module>omoponfhir-r4-server</module>
        </modules>
```

**Comment by gkowalski** [comment]
Well as a test I checked out branch "5.4" then went to the parent folder and ran 

```
docker build -t omoponfhir .
... deleted ...

Downloading from ohdsi: https://repo.ohdsi.org:8085/nexus/content/repositories/releases/com/google/api/gax/1.56.0/gax-1.56.0.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/google/api/gax/1.56.0/gax-1.56.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/google/api/gax/1.56.0/gax-1.56.0.pom (2.3 kB at 166 kB/s)
Downloading from ohdsi: https://repo.ohdsi.org:8085/nexus/content/repositories/releases/org/threeten/threetenbp/1.4.4/threetenbp-1.4.4.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/threeten/threetenbp/1.4.4/threetenbp-1.4.4.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/threeten/threetenbp/1.4.4/threetenbp-1.4.4.pom (32 kB at 1.5 MB/s)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] omoponfhir-omopv5-sql 1.3.0 ........................ FAILURE [  8.641 s]
[INFO] omoponfhir-omopv5-r4-mapping 1.2.2 ................. SKIPPED
[INFO] OMOPonFHIR RESTful Server 1.2.2 .................... SKIPPED
[INFO] OMOPonFHIR-R4 1.0.0 ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.741 s
[INFO] Finished at: 2022-07-19T19:43:59Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project omoponfhir-omopv5-sql: Could not resolve dependencies for project edu.gatech.chai:omoponfhir-omopv5-sql:jar:1.3.0: Failed to collect dependencies at org.ohdsi.sql:SqlRender:jar:1.6.4: Failed to read artifact descriptor for org.ohdsi.sql:SqlRender:jar:1.6.4: Could not transfer artifact org.ohdsi.sql:SqlRender:pom:1.6.4 from/to ohdsi (https://repo.ohdsi.org:8085/nexus/content/repositories/releases): Unrecognized SSL message, plaintext connection? -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
The command '/bin/sh -c mvn clean install' returned a non-zero code: 1
$~/docker/omoponfhir53]$
```

**Comment by gkowalski** [comment]
Checking out 5.4 branch and running clean install : 

```
$ mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< edu.gatech.chai:omoponfhir-omopv5-sql >----------------
[INFO] Building omoponfhir-omopv5-sql 1.3.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from ohdsi: https://repo.ohdsi.org:8085/nexus/content/repositories/releases/org/ohdsi/sql/SqlRender/1.6.4/SqlRender-1.6.4.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.654 s
[INFO] Finished at: 2022-07-20T10:07:47-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project omoponfhir-omopv5-sql: Could not resolve dependencies for project edu.gatech.chai:omoponfhir-omopv5-sql:jar:1.3.0: Failed to collect dependencies at org.ohdsi.sql:SqlRender:jar:1.6.4: Failed to read artifact descriptor for org.ohdsi.sql:SqlRender:jar:1.6.4: Could not transfer artifact org.ohdsi.sql:SqlRender:pom:1.6.4 from/to ohdsi (https://repo.ohdsi.org:8085/nexus/content/repositories/releases): transfer failed for https://repo.ohdsi.org:8085/nexus/content/repositories/releases/org/ohdsi/sql/SqlRender/1.6.4/SqlRender-1.6.4.pom: Unsupported or unrecognized SSL message -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by myungchoi** [comment]
That's OHDSI maven library issue...  In the pom file, there is repositories section. Please check if you have https:// instead of http:// for the sqlRender library.  Recent changes in Maven requires https. The OHDSI server does not properly handle this when http:// is used for the link. 

Please let me know how the mvn clean install goes after you modify that.

**Comment by myungchoi** [comment]
If https is not working, please try with http://, which will fail. Then, change it back to https and try the mvn clean install again. Sometime, you need to do it several times. I think it's related to timeout on the server.... Recently, the OHDSI maven server is becoming bit unstable...

**Comment by gkowalski** [comment]
Well a real hack as I not only had to change the https -> http , but also hack Maven by commenting out the 

```
  <mirror>
      <id>maven-default-http-blocker</id>
      <mirrorOf>external:http:*</mirrorOf>
      <name>Pseudo repository to mirror external repositories initially using HTTP.</name>
      <url>http://0.0.0.0/</url>
      <blocked>true</blocked>
    </mirror>
```
in the ~mvn/conf/settings.xml 

```
 $ mvn --version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /home/crdw/bin/mvn
Java version: 1.8.0_332, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.332.b09-2.el8_6.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-348.23.1.el8_5.x86_64", arch: "amd64", family: "unix"
```

```
 [INFO]
[INFO] ----------------< edu.gatech.chai:omoponfhir-r4-server >----------------
[INFO] Building OMOPonFHIR RESTful Server 1.2.2                           [3/4]
[INFO] --------------------------------[ war ]---------------------------------
[WARNING] The POM for edu.gatech.chai:omoponfhir-omopv6-r4-mapping:jar:1.2.3 is missing, no dependency information available
[WARNING] The artifact org.hibernate:hibernate-validator:jar:6.1.5.Final has been relocated to org.hibernate.validator:hibernate-validator:jar:6.1.5.Final
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] omoponfhir-omopv5-sql 1.3.0 ........................ SUCCESS [  0.704 s]
[INFO] omoponfhir-omopv5-r4-mapping 1.2.2 ................. SUCCESS [  0.252 s]
[INFO] OMOPonFHIR RESTful Server 1.2.2 .................... FAILURE [  0.197 s]
[INFO] OMOPonFHIR-R4 1.0.0 ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.229 s
[INFO] Finished at: 2022-07-20T13:33:20-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project omoponfhir-r4-server: Could not resolve dependencies for project edu.gatech.chai:omoponfhir-r4-server:war:1.2.2: edu.gatech.chai:omoponfhir-omopv6-r4-mapping:jar:1.2.3 was not found in https://oss.sonatype.org/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of oss-snapshots has elapsed or updates are forced -> [Help 1]
```

Now it's failing on the omoponfhir-r4-server ...

**Comment by myungchoi** [comment]
> Well a real hack as I not only had to change the https -> http , but also hack Maven by commenting out the
> 
> ```
>   <mirror>
>       <id>maven-default-http-blocker</id>
>       <mirrorOf>external:http:*</mirrorOf>
>       <name>Pseudo repository to mirror external repositories initially using HTTP.</name>
>       <url>http://0.0.0.0/</url>
>       <blocked>true</blocked>
>     </mirror>
> ```
> 
> in the ~mvn/conf/settings.xml
> 
> ```
>  $ mvn --version
> Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
> Maven home: /home/crdw/bin/mvn
> Java version: 1.8.0_332, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.332.b09-2.el8_6.x86_64/jre
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "4.18.0-348.23.1.el8_5.x86_64", arch: "amd64", family: "unix"
> ```
> 
>  ```
>  [INFO]
> [INFO] ----------------< edu.gatech.chai:omoponfhir-r4-server >----------------
> [INFO] Building OMOPonFHIR RESTful Server 1.2.2                           [3/4]
> [INFO] --------------------------------[ war ]---------------------------------
> [WARNING] The POM for edu.gatech.chai:omoponfhir-omopv6-r4-mapping:jar:1.2.3 is missing, no dependency information available
> [WARNING] The artifact org.hibernate:hibernate-validator:jar:6.1.5.Final has been relocated to org.hibernate.validator:hibernate-validator:jar:6.1.5.Final
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] omoponfhir-omopv5-sql 1.3.0 ........................ SUCCESS [  0.704 s]
> [INFO] omoponfhir-omopv5-r4-mapping 1.2.2 ................. SUCCESS [  0.252 s]
> [INFO] OMOPonFHIR RESTful Server 1.2.2 .................... FAILURE [  0.197 s]
> [INFO] OMOPonFHIR-R4 1.0.0 ................................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  1.229 s
> [INFO] Finished at: 2022-07-20T13:33:20-05:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project omoponfhir-r4-server: Could not resolve dependencies for project edu.gatech.chai:omoponfhir-r4-server:war:1.2.2: edu.gatech.chai:omoponfhir-omopv6-r4-mapping:jar:1.2.3 was not found in https://oss.sonatype.org/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of oss-snapshots has elapsed or updates are forced -> [Help 1]
> ```
> 
> Now it's failing on the omoponfhir-r4-server ...

I don't know how this issue being not tracked. Are you still having an issue? According to the error message, it seems like the omoponfhir-r4-server is pointing to wrong mapper jar.
