### ISSUE TITLE
5.4 branch sql issue text = integer

### ISSUE THREAD

**Issue by kevinwangcanada** [omoponfhir/omoponfhir-omopv5-sql#17]
Hi there, thank you for your work on omop on fhir. really nice!

I tried to build it on my laptop. I got all 3 projects built successfully. it can connect to my local postgres db and I go to http://localhost:8080/omoponfhir-r4-server and the hapi fhir server shows up nicely with all the resources from my local db. however, when I try to do a search using patient id. I got this error:

Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: text = integer
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 481
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:243)
	at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
	at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
	at edu.gatech.chai.omopv5.dba.service.BaseEntityServiceImp.runCountQuery(BaseEntityServiceImp.java:209)
	at edu.gatech.chai.omopv5.dba.service.BaseEntityServiceImp.getSize(BaseEntityServiceImp.java:522)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy28.getSize(Unknown Source)
	at edu.gatech.chai.omoponfhir.omopv5.r4.mapping.OmopObservation.getSize(OmopObservation.java:1889)
	at edu.gatech.chai.omoponfhir.omopv5.r4.mapping.OmopObservation.getSize(OmopObservation.java:1866)
	at edu.gatech.chai.omoponfhir.omopv5.r4.mapping.OmopObservation.<init>(OmopObservation.java:110)
	at edu.gatech.chai.omoponfhir.omopv5.r4.provider.ObservationResourceProvider.<init>(ObservationResourceProvider.java:70)
	at edu.gatech.chai.omoponfhir.servlet.RestfulServlet.initialize(RestfulServlet.java:104)
	at ca.uhn.fhir.rest.server.RestfulServer.init(RestfulServer.java:1346)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1173)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1118)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1011)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4952)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5266)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

I have used debug and got the following sql script from the program.

select count(*) as count from visit_occurrence visit_occurrence left join f_person fPerson on visit_occurrence.person_id=fPerson.person_id left join person person on visit_occurrence.person_id=person.person_id left join concept visitConcept on visit_occurrence.visit_concept_id=visitConcept.concept_id left join concept visitTypeConcept on visit_occurrence.visit_type_concept_id=visitTypeConcept.concept_id left join provider provider on visit_occurrence.provider_id=provider.provider_id left join care_site careSite on visit_occurrence.care_site_id=careSite.care_site_id left join concept visitSourceConcept on visit_occurrence.visit_source_concept_id=visitSourceConcept.concept_id left join concept admittedFromConcept on visit_occurrence.admitted_from_concept_id=admittedFromConcept.concept_id left join concept dischargedToConcept on visit_occurrence.discharged_to_concept_id=dischargedToConcept.concept_id where (fPerson.person_id = 1)

when I run it in sqlworkbench/J and it returns the correct count which is 7. 

can you advise what I could do to fix this ?

Thanks,
Kevin

**Comment by myungchoi** [comment]
Kevin, can you post the FHIR query?

**Comment by kevinwangcanada** [comment]
Hi Myungchoi,

this is what is shown in the url:
http://localhost:8080/omoponfhir-r4-server/search?serverId=home&pretty=true&_summary=&resource=Encounter&param.0.0=&param.0.1=1&param.0.name=patient&param.0.type=reference&sort_by=&sort_direction=&resource-search-limit=

and this is shown on the hapi fhir rendered page as GET request:
GET http://localhost:8080/omoponfhir-r4-server/fhir/Encounter?patient=1&_pretty=true

**Comment by kevinwangcanada** [comment]
![Screen Shot 2022-11-15 at 9 42 25 PM](https://user-images.githubusercontent.com/1420292/202070741-de9d7e26-04f9-4731-89fd-d36a75b0c18e.png)

**Comment by kevinwangcanada** [comment]
Hi Myungchoi,

I was able to resolve the issue finally. It is due to incorrect data type in f_observation_view. 

the ddl sql script I got from the zip file does not specify the data type for some fields. so they are created as text instead of integer. I modified the ddl script to something like:

CREATE OR REPLACE VIEW cdm.f_observation_view
 AS
 SELECT observation.observation_id,
    observation.person_id,
    observation.observation_concept_id,
    observation.observation_date,
    NULL::text AS observation_time,
    observation.observation_type_concept_id,
    NULL::integer AS observation_operator_concept_id,
    observation.value_as_number,
    observation.value_as_string,
    observation.value_as_concept_id,
    observation.qualifier_concept_id,
    observation.unit_concept_id,
    NULL::integer AS range_low,
    NULL::integer AS range_high,
    observation.provider_id,
    observation.visit_occurrence_id,
    observation.visit_detail_id,
    observation.observation_source_value,
    observation.observation_source_concept_id,
    observation.unit_source_value,
    NULL::integer AS value_source_value,
    observation.qualifier_source_value
   FROM cdm.observation;

and then it worked for me. I also had to create the f_immunization_view as well which I found the ddl script from an earlier version.

Thanks,
Kevin
